#theme: jekyll-theme-slate
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
title: MeherY
description: Enterprise.Social.Communication
logo: "https://cdn.jsdelivr.net/gh/mehery-soccom/mehery-content@main/static/app/logo/bg-x-icon.png"
